export const KOREAN_GAME_SERVERS = [
    '초코보',
    '모그리',
    '카벙클',
    '톤베리',
    '펜리르'
];

export const CHINESE_GAME_SERVERS = [
    'HongYuHai',
    'ShenYiZhiDi',
    'LaNuoXiYa',
    'HuanYingQunDao',
    'MengYaChi',
    'YuZhouHeYin',
    'WoXianXiRan',
    'ChenXiWangZuo',
    'BaiYinXiang',
    'BaiJinHuanXiang',
    'ShenQuanHen',
    'ChaoFengTing',
    'LvRenZhanQiao',
    'FuXiaoZhiJian',
    'Longchaoshendian',
    'MengYuBaoJing',
    'ZiShuiZhanQiao',
    'YanXia',
    'JingYuZhuangYuan',
    'MoDuNa',
    'HaiMaoChaWu',
    'RouFengHaiWan',
    'HuPoYuan',
    'ShuiJingTa2',
    'YinLeiHu2',
    'TaiYangHaiAn2',
    'YiXiuJiaDe2',
    'HongChaChuan2'
];

export const GAME_SERVERS = [
    'Adamantoise',
    'Aegis',
    'Alexander',
    'Anima',
    'Asura',
    'Atomos',
    'Bahamut',
    'Balmung',
    'Behemoth',
    'Belias',
    'Brynhildr',
    'Cactuar',
    'Carbuncle',
    'Cerberus',
    'Chocobo',
    'Coeurl',
    'Diabolos',
    'Durandal',
    'Excalibur',
    'Exodus',
    'Faerie',
    'Famfrit',
    'Fenrir',
    'Garuda',
    'Gilgamesh',
    'Goblin',
    'Gungnir',
    'Hades',
    'Hyperion',
    'Ifrit',
    'Ixion',
    'Jenova',
    'Kujata',
    'Lamia',
    'Leviathan',
    'Lich',
    'Louisoix',
    'Malboro',
    'Mandragora',
    'Masamune',
    'Mateus',
    'Midgardsormr',
    'Moogle',
    'Odin',
    'Omega',
    'Pandaemonium',
    'Phoenix',
    'Ragnarok',
    'Ramuh',
    'Ridill',
    'Sargatanas',
    'Shinryu',
    'Shiva',
    'Siren',
    'Tiamat',
    'Titan',
    'Tonberry',
    'Typhon',
    'Ultima',
    'Ultros',
    'Unicorn',
    'Valefor',
    'Yojimbo',
    'Zalera',
    'Zeromus',
    'Zodiark',

// New for 5.0
    'Spriggan',
    'Twintania',

// Materia, 6.08, Oceania DC
    'Bismarck',
    'Ravana',
    'Sephirot',
    'Sophia',
    'Zurvan',

    // Dynamis, 6.28, NA DC
    'Halicarnassus',
    'Maduin',
    'Marilith',
    'Seraph',
    'Cuchulainn',
    'Golem',
    'Kraken',
    'Rafflesia',

    // Chinese servers
    ...CHINESE_GAME_SERVERS,

    // Korean servers
    ...KOREAN_GAME_SERVERS,

    // New for 6.18
    'Alpha',
    'Phantom',
    'Raiden',
    'Sagittarius'
];